apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metrics-ingress
  namespace: default
  annotations:
    # Add this to get a Tailscale-issued certificate
    tailscale.com/tags: "tag:k8s"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: hungry-echoes
      port:
        number: 8081