# network-policies.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hungry-echoes-network-policy
spec:
  podSelector:
    matchLabels:
      app: hungry-echoes
  policyTypes:
    - Ingress
  ingress:
    # Allow public traffic through ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080  # Application port
    # Allow metrics traffic only from Tailscale
    - from:
        - namespaceSelector:
            matchLabels:
              # kubernetes.io/metadata.name: tailscale
               kubernetes.io/metadata.name: monitoring
        - podSelector:
            matchLabels:
              # app: tailscale-metrics-proxy
              app: prometheus
      ports:
        - protocol: TCP
          port: 8081  # Metrics port
# ---
# Additional network policy for Tailscale proxy
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: tailscale-metrics-policy
#   namespace: tailscale
# spec:
#   podSelector:
#     matchLabels:
#       app: tailscale-metrics-proxy
#   policyTypes:
#     - Ingress
#     - Egress
#   ingress:
#     - from:
#         - namespaceSelector:
#             matchLabels:
#               kubernetes.io/metadata.name: tailscale
#   egress:
#     - to:
#         - namespaceSelector: {}
#       ports:
#         - protocol: TCP
#           port: 8081