# monitoring/config.yaml

# Create namespace first
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring

---
# Then ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s      # How frequently to scrape targets
      evaluation_interval: 15s   # How frequently to evaluate rules

    scrape_configs:
      - job_name: 'hungry-echoes'
        static_configs:
          - targets: ['metrics.hungryechoes.com']  # Updated to use subdomain
        metrics_path: '/metrics'
        scheme: 'http'          # Use 'https' if you enable TLS
        # Optional: Add basic auth if you secure the endpoint
        # basic_auth:
        #   username: <username>
        #   password: <password>