# postgres/db-init-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  labels:
    app: postgres
    component: database
data:
  init.sql: |
    -- Create schema if it doesn't exist
    CREATE SCHEMA IF NOT EXISTS corporate;

    -- Create table if it doesn't exist
    CREATE TABLE IF NOT EXISTS corporate.jargons (
        id SERIAL PRIMARY KEY,
        sentence TEXT NOT NULL
    );

    -- Delete existing data to avoid duplicates
    TRUNCATE corporate.jargons;

    -- Insert corporate jargon sentences
    INSERT INTO corporate.jargons (sentence) VALUES 
        ('Echoing what %s said, %s is critical to our business but I also believe we need to stay hungry'),
        ('Piggybacking off %s''s point, %s is a game-changer, and we must maintain our entrepreneurial spirit'),
        ('To circle back to %s''s insight, %s moves the needle, though we should keep our startup mindset'),
        ('Building on %s''s contribution, %s is mission-critical, yet we must preserve our growth mentality'),
        ('Leveraging %s''s perspective, %s drives our core metrics, while maintaining our innovative edge'),
        ('Aligning with %s''s viewpoint, %s optimizes our synergies, as we continue our disruptive journey'),
        ('Synchronizing with %s''s strategy, %s maximizes stakeholder value, while keeping our agile approach'),
        ('In harmony with %s''s framework, %s accelerates our value proposition, as we maintain our competitive advantage'),
        ('Dovetailing with %s''s analysis, %s enhances our market position, while sustaining our forward momentum'),
        ('Resonating with %s''s assessment, %s empowers our strategic initiatives, as we preserve our dynamic capabilities');