# monitoring/egress-metrics.yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus-egress
  namespace: monitoring
  annotations:
    tailscale.com/tailnet-fqdn: default-metrics-ingress-svc.tail81089.ts.net
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  externalName: unused   # any value - will be overwritten by operator
  type: ExternalName
