apiVersion: v1
kind: Service
metadata:
  name: hungry-echoes-metrics  # Updated name
  namespace: default
  annotations:
    net.gke.io/multi-cluster-service-name: hungry-echoes-metrics  # Updated name
spec:
  ports:
    - name: metrics
      port: 8081
      targetPort: 8081
  type: ClusterIP