apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: default
spec:
  containers:
  - name: debug-container
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    resources:
      requests:
        cpu: "50m"      # Minimum CPU allocation
        memory: "64Mi"  # Minimum memory allocation
      limits:
        cpu: "100m"     # Maximum CPU allocation
        memory: "128Mi" # Maximum memory allocation