apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: he-user
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Will be replaced by actual password
  POSTGRES_DB: phrases