apiVersion: apps/v1
kind: Deployment
metadata:
  name: hungry-echoes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hungry-echoes
  template:
    metadata:
      labels:
        app: hungry-echoes
    spec:
      containers:
      - name: hungry-echoes
        image: gcr.io/tailscale-tests-and-demos/hungry-echoes:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "postgres.default.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata:
  name: hungry-echoes
spec:
  selector:
    app: hungry-echoes
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
