apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-scrape-configs
  namespace: monitoring
data:
  prometheus-additional-scrape-configs.yaml: |
    scrape_configs:
      - job_name: 'hungry-echoes'
        static_configs:
          - targets: ['metrics.hungryechoes.com:8081']